---
title: "data_viz_yunyang"
author: "Yunyang Zhong"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(kableExtra)
survey <- read_csv("Patient_Characteristics_Survey__PCS___2017.csv")
```

```{r}
data.frame(variable = c("Transgender", "Mental Illness", "Race", "Hispanic Ethnicity", "Sexual Orientation"), meaning = c("YES or NO", "YES or NO", "WHITE ONLY, BLACK ONLY, or MULTI-RACIAL", "YES or NO", "BISEXUAL, LESBIAN/GAY or STRAIGHT/HETEROSEXUAL")) %>% 
  kbl() %>% 
  kable_classic(position = "center", full_width = F)
```


```{r}
table(survey$Transgender)
table(survey$`Mental Illness`)
table(survey$Race)
table(survey$`Hispanic Ethnicity`)
table(survey$`Sexual Orientation`)
```

```{r}
survey %>% 
  filter(Transgender == "NO, NOT TRANSGENDER" | Transgender == "YES, TRANSGENDER") %>% 
  ggplot(aes(x = Transgender, fill = `Mental Illness`)) +
  geom_bar(position = "fill")
```

```{r}
survey %>% 
  filter(Transgender == "NO, NOT TRANSGENDER" | Transgender == "YES, TRANSGENDER") %>% 
  filter(Race == "WHITE ONLY" | Race == "BLACK ONLY" | Race == "MULTI-RACIAL") %>% 
  ggplot(aes(x = Transgender, fill = Race)) +
  geom_bar(position = "fill")
```

```{r}
survey %>% 
  filter(Race == "WHITE ONLY" | Race == "BLACK ONLY" | Race == "MULTI-RACIAL") %>% 
  ggplot(aes(x = Race, fill = `Mental Illness`)) +
  geom_bar(position = "fill")
```

```{r}
survey %>% 
  filter(Transgender == "NO, NOT TRANSGENDER" | Transgender == "YES, TRANSGENDER") %>% 
  filter(`Alcohol Related Disorder` == "YES" | `Alcohol Related Disorder` == "NO") %>% 
  ggplot(aes(x = Transgender, fill = `Alcohol Related Disorder`)) +
  geom_bar(position = "fill")
```

```{r}
survey %>% 
  filter(Transgender == "NO, NOT TRANSGENDER" | Transgender == "YES, TRANSGENDER") %>% 
  filter(`Drug Substance Disorder` == "YES" | `Drug Substance Disorder` == "NO") %>% 
  ggplot(aes(x = Transgender, fill = `Drug Substance Disorder`)) +
  geom_bar(position = "fill")
```

```{r}
survey %>% 
  filter(`Alcohol Related Disorder` == "YES" | `Alcohol Related Disorder` == "NO") %>% 
  ggplot(aes(x = `Alcohol Related Disorder`, fill = `Mental Illness`)) +
  geom_bar(position = "fill")
```

```{r}
survey %>% 
  filter(`Drug Substance Disorder` == "YES" | `Drug Substance Disorder` == "NO") %>% 
  ggplot(aes(x = `Drug Substance Disorder`, fill = `Mental Illness`)) +
  geom_bar(position = "fill")
```

